name: CI

on:
  pull-request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        run: npm ci

      - name: Test Client App
        run: npm run test:client

      - name: Test Backend App
        run: npm run test:api
